language: python
python:
  - "3.7-dev" # https://github.com/travis-ci/docs-travis-ci-com/blob/master/user/languages/python.md
install:
  - pip install -U pip
  - sudo apt-get install python-enchant
  - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
  - source $HOME/.poetry/env
  - poetry install -v
script:
  - poetry run pytest --cov=python_package tests -W ignore